### ISSUE TITLE
Compile error in Visual Studio Mac

### ISSUE THREAD

**Issue by gameunite** [ssannandeji/Zenject-2019#560]
Everything works fine in 2018.3.0b1 but not in 2018.3.0.b5. I'm using Zenject 7.3.0.

Here's the error log:
> Error CS1617: Invalid option '7.3' for /langversion. Use '/langversion:?' to list supported values. (CS1617) (Zenject)

**Comment by gameunite** [comment]
It's now working fine in 2018.3.0b6 so I'll just close this.
